### ISSUE TITLE
Files from _config.yml not rendering properly

### ISSUE THREAD

**Issue by taylorreiter** [datacarpentry/organization-genomics#79] opened 2019-02-04 12:48 UTC
The following pages are rendering improperly:
Setup
Reference
Code of conduct

@ErinBecker  fixed a similar issue by editing the `_config.yml` file in the wrangling-genomics lesson.

**Comment by hoytpr** [comment] 2019-02-04 15:32
Seems to be working now. Can you confirm, being sure to refresh the page your browser? Thanks very much!
Peter

**Comment by taylorreiter** [comment] 2019-02-04 16:51
I opened in a new browser, and it is still not rendering properly. I'm attaching a `png` here!
![screen shot 2019-02-04 at 11 49 36 am](https://user-images.githubusercontent.com/23057646/52223178-14fd3780-2873-11e9-8208-dabf531e511e.png). 

The code of conduct looks similar

**Comment by hoytpr** [comment] 2019-02-04 17:19
You are correct. Same thing happened at https://github.com/datacarpentry/organization-genomics/pull/77

EDIT: ignore instructions below given previously. They only worked temporarily. The changes in config.yml that @taylorreiter suggested by @ErinBecker are correct. I have submitted pull request #86 that should close #78 and #77 (again). 

------------------------------
To fix, change the YAML headings in "Setup.md",  "Code-of_conduct.md" and "Reference.md" by removing the permalinks completely, make sure the Setup page and Code of Conduct page are using a "page" layout, and the References page is using a "references" layout, it should fix everything. 
Thanks!

**Comment by tracykteal** [comment] 2019-03-06 16:34
Looks like https://github.com/datacarpentry/organization-genomics/pull/86 fixes this. Looks fine now on my computer. @taylorreiter maybe you could confirm though?

Thanks @hoytpr for tracking this down.

**Comment by ErinBecker** [comment] 2019-03-06 18:14
Thanks @hoytpr! I've also checked and confirmed these files render properly on my computer. Closing this issue.

**Closed as completed by ErinBecker** 2019-03-06 18:14 UTC
