### ISSUE TITLE
Data tidiness file download issue

### ISSUE THREAD

**Issue by CronicSloth** [datacarpentry/organization-genomics#146] opened 2022-11-05 14:42 UTC
The link for downloading the cleaned datasheet in the solution did not work for me and instead opens up a webpage with the data when I right click with no option for downloading it 
---

**Comment by hoytpr** [comment] 2023-01-12 20:54
Hi @CronicSloth I can't seem to reproduce your issue. What operating system are you using?

**Comment by CronicSloth** [comment] 2023-01-24 17:46
Hello this email got buried in my inbox so sorry for just getting back to you. After talking with a few other people at my institution we think it was just an issue with how we set up our local cloud computer so its not relevant to other users. Thanks for following up tho -Jude
________________________________

**Comment by JCSzamosi** [comment] 2023-03-07 15:44
Thanks for providing the update @CronicSloth! I will close this issue now, but feel free to re-open it if it turns out something else is going on.

**Closed as completed by JCSzamosi** 2023-03-07 15:44 UTC
